### ISSUE TITLE
isSuccessful is true even if user closes the review window

### ISSUE THREAD

**Issue by ShivamJoker** [ravirupareliya/rn-in-app-review#1]
```js
const launchReview = () => {
  RnInAppReview.launchReviewFlow(async (isSuccessful) => {
    if (isSuccessful) {
      ToastAndroid.showWithGravity(
        'Thank You!',
        ToastAndroid.SHORT,
        ToastAndroid.CENTER,
      );
      await setAppData(userActionId, 'given');
    }
  });
};
```
Please fix it and thanks for the library :)

**Comment by ravirupareliya** [comment]
@ShivamJoker Thanks for giving this library a try.
Yes, it is desired behaviour and we can not get status like user has reviewed or not. Even if dialog did not show, it will return as true only. This is mentioned in android document as well.

https://developer.android.com/guide/playcore/in-app-review/kotlin-java#kotlin

**Comment by ShivamJoker** [comment]
That's really sad is it same with iOS also ?

**Comment by ravirupareliya** [comment]
Closing this issue, as it is native functionality.
